name: Build

on:
  push:
  schedule:
    - cron: '30 22 2 * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build
        run: |
          podman build -t "${GITHUB_REPOSITORY}" .
      - name: Test invocation
        run: |
          podman run -i -t --rm --systemd=always ${GITHUB_REPOSITORY} \
                     /bin/echo "Hello world"
      - name: Test exit status propagation
        run: |
          podman run -i -t --rm --systemd=always ${GITHUB_REPOSITORY} \
                       return 42 || RC=$?
          echo Exit status $RC
          [ $RC -eq 42 ]
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          podman login -u "${{ secrets.DOCKER_USERNAME }}" \
                       -p "${{ secrets.DOCKER_PASSWORD }}"
          podman push "${GITHUB_REPOSITORY}"
