name: Build

on:
  push:
  schedule:
    - cron: '30 22 2 * *'

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build
        run: |
          sudo podman build -t "${GITHUB_REPOSITORY}" .
      - name: Test
        run: |
          sudo podman run -i -t --rm --systemd=always mcb30/fedora-systemd \
                          /bin/echo "Hello world"
      - name: Publish
        run: |
          sudo podman login -u "${{ secrets.DOCKER_USERNAME }}" \
                            -p "${{ secrets.DOCKER_PASSWORD }}"
          sudo podman push "${GITHUB_REPOSITORY}"
